### ISSUE TITLE
gatewayMerchantId is stripped away

### ISSUE THREAD

**Issue by Verseth** [clearhaus/aliquot#20]
Google Pay docs demand that processors verify the `gatewayMerchantId` value in the Encrypted Message payload.

The current implementation of Aliquot strips away this crucial parameter since it isn't defined in `Aliquot::Validator::EncryptedMessageContract`.

Here is a snippet:

```rb
output = Aliquot::Validator::EncryptedMessageSchema.call(
  {
    "gatewayMerchantId"=>"some:value", # this parameter has to be checked
    "messageExpiration"=>"3246346346",
    "messageId"=>"2323434534434fgdgdfg",
    "paymentMethod"=>"CARD",
    "paymentMethodDetails"=> {
      "expirationYear"=>2032,
      "expirationMonth"=>9,
      "pan"=>"019742579823658273",
      "authMethod"=>"CRYPTOGRAM_3DS",
      "cryptogram"=>"sikdhgiuwegtf78623rt"
    }
  }
).to_h

# and yet it is removed
output[:gatewayMerchantId] #=> nil
```

**Comment by brorbw** [comment]
@Verseth can you provide a link to the documentation?

**Comment by Verseth** [comment]
Sure, keep in mind that you need to be authorized to view it https://developers.google.com/pay/api/processors/guides/implementation/understand-our-payload#message-encryption

**Comment by Verseth** [comment]
I've opened a PR that resolves this issue https://github.com/clearhaus/aliquot/pull/21

**Comment by Verseth** [comment]
Here are some links

https://developers.google.com/pay/api/web/reference/request-objects#gateway
https://developers.google.com/pay/api/processors/guides/implementation/understand-our-payload#message-encryption

**Comment by Verseth** [comment]
Hi, are there any updates regarding your position on this PR?

**Comment by brorbw** [comment]
@Verseth we at looking into is now
